### ISSUE TITLE
Vector mbtiles not working

### ISSUE THREAD

**Issue by caerandir** [bojko108/mobile-tile-server#10]
I've successfully installed and configured the server. When I use raster mbtiles, it works. However, if I use vector mbtiles, there seems to be an issue - which admittedly may also be an issue of the consuming app. A bit more details:

- when I open http://localhost:{port}/mbtiles in my browser, I get a list of all my mbtiles files, so all are recognized, and shown data is correct.
- if I open the leaflet preview, with raster mbtiles I get a nice preview.
- If I open the laeflet preview for a vector mbtiles file, I get an empty screen, partly white, partly gray.
- When I configure http://localhost:{port}/mbtiles?tileset=my.mbtiles&z={z}&x={x}&y={y} in my app, with raster maps I get the raster tiles and all is shiny.
- If I configure the same URL for vector mbtiles, my app does not seem to recognize the data received or does not get any data at all.
- If I enter into the browser http://localhost:{port}/mbtiles?tileset=my.mbtiles&z=13&x=4259&y=2754 which I know that it exists in the mbtiles-DB, I get "The image .... cannot be displayed because it contains errors", and Firefox seems to believe it is a PNG file.

My gut feeling: you statically(?) deliver 'Content-type: image/png'. Would there be a chance to state the content type, e.g. by changing the URL to http://localhost:{port}/mbtiles?tileset=my.mbtiles&z={z}&x={x}&y={y}&type=pbf --> which would deliver a PBF file (i.e. vector tile)?

EDIT: Looking at the response from a different tile server on Linux there does not seem to be a valid content type, so having the option of keeping it empty/delivering no Content-type header at all would be nice to also have.
EDIT EDIT (sorry...): Mapbox seems to give Content type application/x-protobuf for PBF data.

**Comment by bojko108** [comment]
Hi,
you are correct, the content type is hardcoded to png... I can change that, but don't think this will solve the issue. The bigger problem is the preview functionality of the application is using Leaflet TileLayer to create a simple map viewer, where to display the data, but the TileLayer supports only images.

In what application you are consuming the vector tiles layer? Probably there, you need to configure the layer type as vector tiles instead of raster tiles.

**Comment by caerandir** [comment]
The App is actually OruxMaps, but not via onlinemapsources.xml, but using the premium feature Mapbox maps. With 10€/year it is affordable, and it allows to include vector offline maps, using Mapbox/Maplibre JSON styles - even mixing vector and raster is possible. Oruxmaps has its own builtin Tileserver, but that one has a severe bug, and I yet did not catch the attention of the App developer (read all about it here: https://oruxmaps.org/forum/index.php?topic=44533.0). So - I hope you're not offended - I mainly plan to use the Mobile Tile Server to work around a bug of OruxMaps... apologies!
That said: Yes, the mapsource is configured as vector, but somehow nothing is displayed. Troubleshooting is not very easy, since I have no error log or messages. Since Oruxmaps can consume vector and raster sources in a style file, I can imagine that it gets confused by the Content-type and switchs to raster, despite being told it is vector. This may also be because there's no file extension for Mbile Tile server - for comparison:
Using the OruxMaps builtin tile server, the URL is http://localhost:8998/MySelfmade.mbtiles/{z}/{x}/{y}.pbf - with your server http://localhost:1886/mbtiles?tileset=MySelfmade.mbtiles&z={z}&x={x}&y={y} - no .pbf.

That the Leaflet preview does not work: That's no problem for me, and not surprising.

Finally: Since you seem to use OruxMaps as well: OruxMaps by now supports mbtiles as "native" raster offline maps even without the premium feature - just put them into the maps directory, update your mapsources, and enjoy :-)

**Comment by bojko108** [comment]
I've developed Mobile Tile Server mainly for my own usage :D, I'm using it for several other applications, which are not yet in the play store. I'm little busy now at the office, but will try to make a new release this weekend so you can test it and see if it helps you solve your problems.

**Comment by caerandir** [comment]
Thanks a lot - and take your time!

**Comment by bojko108** [comment]
Hi @caerandir ,
I've created a new release - [https://github.com/bojko108/mobile-tile-server/releases/tag/v4.6](https://github.com/bojko108/mobile-tile-server/releases/tag/v4.6). The content type is now set according to the format parameter of the MBTiles file. I did not found a way to test this rather than just checking the responses for simple queries for individual tiles. The results are returned with 'application/octet-stream' content type.

**Comment by bojko108** [comment]
Ok, I've made another change - the content encoding is now set correctly and I was able to successfully serve MBTiles file with vector tiles in PBF format. I've changed also the url for the mbtiles requests:
- old url: http://localhost:1886/mbtiles?tileset=countries.mbtiles&z={z}&x={x}&y={y}
- new url: **http://localhost:1886/mbtiles/countries.mbtiles/{z}/{x}/{y}**

You can take the updated apk file from the latest release: https://github.com/bojko108/mobile-tile-server/releases/tag/v4.6

**Comment by caerandir** [comment]
Cool - that did the trick, it is now working! Thank you very much for taking care!!!
