### ISSUE TITLE
[MBTiles Tilesets]: Mbtiles file not working

### ISSUE THREAD

**Issue by ntvkhoasgt** [bojko108/mobile-tile-server#4]
Hi, @bojko108 
Mbtiles tileset is not working with me.

Below is my setup:
1. Device:
- Samsung tab s7
- Android 12

2. Mbtiles tile set is generate from this (opf file)[https://download.geofabrik.de/north-america/us/california/socal.html] with (tilemaker)[https://github.com/systemed/tilemaker]  

3. Reproduction:
- Build and install apk from branch master
- Touch "Start" button to start the server and create the server root directory.
- Touch "Stop" button to stop the server
- Copy socal.mbtiles to `/storage/emulated/0/Downloads/mbtiles/socal.mbtiles	
- Touch "Start" button to start the server.

My issues are:
1. Access http://localhost:1886/mbtiles is showing nothing
2. Run a simple leaflet demonstration with url `http://localhost:1886/mbtiles?tileset=socal&z={z}&x={x}&y={y}` is showing nothing also.

Did I missed something?
Please help me to confirm if my setup is working or not. Thank you.

**Comment by bojko108** [comment]
Hi @ntvkhoasgt,
I don't think there is an issue with your mbtiles file. The problem could be the android version on your device. I didn't tested the application on Android 12 till now.

You can try the following things:

- try to install the app from Google Play - [Mobile Tile Server](https://play.google.com/store/apps/details?id=com.bojko108.mobiletileserver)
- set the root directory in app settings to "/storage/emulated/0/Downloads". The default directory is "/storage/emulated/0/MobileTileServer". You could also try putting your map files there. 
- be sure to give storage permissions to the app
- start the server and go to [http://localhost:1886/](http://localhost:1886/).

**Comment by ntvkhoasgt** [comment]
@bojko108

I followed your instructions with Samsung tab A8 (Android 11) but it still doesn't work.

Can you give a sample mbtiles? And what android version have you tested?

Anyway, dir tiles still working fine. But mbtiles wasn't

**Comment by bojko108** [comment]
Hi, I think I'm not following you correctly. I thought you are not able to start the server, but now you are saying the static tiles are accessible. If you are able to open [http://localhost:1886/](http://localhost:1886/) then the server is working and the issue is with your mbtiles file. I've uploaded a [sample mbtiles file generated from QGIS v3](https://wetransfer.com/downloads/cb2147469fbf7b2577ddea30dd1da45020221015090310/dccac163aa4fa61ae98c24ad3df9245e20221015090323/12d714) (its extent is near Sofia (Bulgaria)).

Try to load this mbtiles file to see if it works for you.

**Comment by ntvkhoasgt** [comment]
@bojko108 ,
Thank you, i will try this and report soon.

**Comment by ntvkhoasgt** [comment]
I'm doing step by step and it not working on pixel 3a xl Android 12.

About android 11, I will test it on Monday 🙇

**Comment by bojko108** [comment]
Hi, I am sorry, but I'm not able to help you with that now. In the coming days I'll try to test with another device ( Samsung TabActive3, Android 12). There could be a problem with the app permissions, more specifically with the file access. The newer versions of Android have specific requirements for the file access. The Android version I tested till now is Android 10 and there is no problem with the mbtiles access.

**Comment by ntvkhoasgt** [comment]
Happy to hear about it in the coming days. 
I will try to test on Emulator Android 10.
Thank you very much.

**Comment by ntvkhoasgt** [comment]
Hi, I'm was tested your file in Android 9 Emulator and it work
<img width="984" alt="Screen Shot 2022-10-19 at 15 14 05" src="https://user-images.githubusercontent.com/67872483/196635355-c40ec83d-f6b3-4518-aed9-fad99c8ff830.png">

**Comment by ntvkhoasgt** [comment]
hi @bojko108, I was fixed this on my local code. 

We need to change new access on Android 10+
https://developer.android.com/training/data-storage/manage-all-files

**Comment by bojko108** [comment]
So you've found the solution :). I thought it's related to the file access permissions, but didn't have time to check it. I'll make some tests and will make a CR for this soon.

Thank you!

**Comment by ntvkhoasgt** [comment]
https://developer.android.com/about/versions/11/privacy/storage#permissions
In Android 11 (API Level 30), when using READ_EXTERNAL_STORAGE only Photo and Media could be accessed able, this reason could provide why it works with the static tiles (it .png).

The mbtiles was .mbtiles and your list files get = 0
<img width="782" alt="Screen Shot 2022-10-20 at 08 48 10" src="https://user-images.githubusercontent.com/67872483/196837020-2c472247-1d8d-47de-a6e9-556b5b0489c5.png">
