### ISSUE TITLE
Can't install under Android 13

### ISSUE THREAD

**Issue by caerandir** [bojko108/mobile-tile-server#8]
When I try to install this app via Google play, it says that it was developed for an older version of Android and I can't install it. Any chance to get an updated version?
Thanks!

**Comment by bojko108** [comment]
Hello,
on what version you are trying to install the app? I have a device with Android 12 and the app is running. The minimum Android version is set to Android 8.0 in the configuration so it should be possible, but I haven't tested it actually.

**Comment by caerandir** [comment]
Hello & thanks for your reply!

 

I'm running Android 13 on my Phone, and Google Play claims it is not compatible with the App. I've no idea if it is worth an experiment to get the APK somewhere and install it manually - if you think this might work, where might I get an APK?

 

Thanks!

 
 

Gesendet: Mittwoch, 29. Mai 2024 um 10:24 Uhr
Von: "Bogdan Hristozov" ***@***.***>
An: "bojko108/mobile-tile-server" ***@***.***>
Cc: "caerandir" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [bojko108/mobile-tile-server] Can't install under Android 13 (Issue #8)


 

Hello,
on what version you are trying to install the app? I have a device with Android 12 and the app is running. The minimum Android version is set to Android 8.0 in the configuration so it should be possible, but I haven't tested it actually.

**Comment by caerandir** [comment]
Stupid me - just realized I can get the APK from the releases page. Still, my phone refuses to install the software directly from the APK... Any chance you might provide an updated version that works for Android 13?

**Comment by bojko108** [comment]
Hi,
I've created a new update for the google play app, but until it is published you can test with the apk from the latest release - https://github.com/bojko108/mobile-tile-server/releases/tag/v4.5. I hope it will be ok now.

Thank you!

**Comment by caerandir** [comment]
Cool - thanks! I was able to install it, and it works! I still have an issue, but I'll open it seperately. This one here can be closed.

Thank you very much again!!!

**Comment by caerandir** [comment]
solvedm can be closed
